{{- if .Values.dpaInstance.deploy -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: cloud-credentials
stringData:
  cloud: |
    [default]
    aws_access_key_id={{ .Values.dpaInstance.minio.user }}
    aws_secret_access_key={{ .Values.dpaInstance.minio.password }}
{{- end -}}
