{{- if eq .Values.dpaInstance.storage "odf" -}}
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: obc-backups
spec:
  storageClassName: openshift-storage.noobaa.io
  generateBucketName: backups
{{- end -}}
