---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oadp-cli-job-sa
  labels:
    {{- include "oadp.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: cli-job-sa
