{{- if .Values.deployOperator }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: redhat-oadp-operator
  labels:
    {{- include "oadp.labels" . | nindent 4 }}
spec:
  channel: {{ .Values.operatorChannel }}
  installPlanApproval: Automatic
  name: redhat-oadp-operator
{{- if .Values.useCatalogSnapshot }}
  source: "{{ .Values.catalogSource.name }}"
  sourceNamespace: {{ .Values.catalogSource.namespace }}
{{- else }}
  source: redhat-operators
  sourceNamespace: openshift-marketplace
{{- end }}
{{- end }}
